---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - rollout.ovice.com
  resources:
  - rolloutscaledowns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rollout.ovice.com
  resources:
  - rolloutscaledowns/finalizers
  verbs:
  - update
- apiGroups:
  - rollout.ovice.com
  resources:
  - rolloutscaledowns/status
  verbs:
  - get
  - patch
  - update
