# permissions for end users to view rolloutscaledowns.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: rolloutscaledown-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: rollout-optimizer-controller
    app.kubernetes.io/part-of: rollout-optimizer-controller
    app.kubernetes.io/managed-by: kustomize
  name: rolloutscaledown-viewer-role
rules:
- apiGroups:
  - rollout.ovice.com
  resources:
  - rolloutscaledowns
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rollout.ovice.com
  resources:
  - rolloutscaledowns/status
  verbs:
  - get
