---
apiVersion: v1
kind: Service
metadata:
  name: rollout-bluegreen-active
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: rollout-sample
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: rollout-bluegreen-preview
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: rollout-sample
  type: ClusterIP
