name: Test

on:
  push:
    branches:
      - master

    tags:
      - v*

  pull_request:

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"
      - name: Testing
        run: |
          go mod download
          make test
