name: Test

on:
  push:
    branches:
      - main

    tags:
      - v*

  pull_request:

jobs:
  unit-test:
    runs-on: utility-staging-amd64

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - name: Testing
        run: |
          go mod download
          make test
